//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChat02.ChatServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Msg", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Msg : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WebChat02.ChatServiceReference.User userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string timeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public WebChat02.ChatServiceReference.User user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                if ((object.ReferenceEquals(this.msgField, value) != true)) {
                    this.msgField = value;
                    this.RaisePropertyChanged("msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string time {
            get {
                return this.timeField;
            }
            set {
                if ((object.ReferenceEquals(this.timeField, value) != true)) {
                    this.timeField = value;
                    this.RaisePropertyChanged("time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string logintimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string logintime {
            get {
                return this.logintimeField;
            }
            set {
                if ((object.ReferenceEquals(this.logintimeField, value) != true)) {
                    this.logintimeField = value;
                    this.RaisePropertyChanged("logintime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChatServiceReference.ChatServiceSoap")]
    public interface ChatServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOnlineUsers", ReplyAction="*")]
        void GetOnlineUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOnlineUsers", ReplyAction="*")]
        System.Threading.Tasks.Task GetOnlineUsersAsync();
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessages", ReplyAction="*")]
        WebChat02.ChatServiceReference.GetMessagesResponse GetMessages(WebChat02.ChatServiceReference.GetMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessages", ReplyAction="*")]
        System.Threading.Tasks.Task<WebChat02.ChatServiceReference.GetMessagesResponse> GetMessagesAsync(WebChat02.ChatServiceReference.GetMessagesRequest request);
        
        // CODEGEN: Generating message contract since element name incoming from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMsg", ReplyAction="*")]
        WebChat02.ChatServiceReference.SendMsgResponse SendMsg(WebChat02.ChatServiceReference.SendMsgRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMsg", ReplyAction="*")]
        System.Threading.Tasks.Task<WebChat02.ChatServiceReference.SendMsgResponse> SendMsgAsync(WebChat02.ChatServiceReference.SendMsgRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        WebChat02.ChatServiceReference.LoginResponse Login(WebChat02.ChatServiceReference.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<WebChat02.ChatServiceReference.LoginResponse> LoginAsync(WebChat02.ChatServiceReference.LoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessages", Namespace="http://tempuri.org/", Order=0)]
        public WebChat02.ChatServiceReference.GetMessagesRequestBody Body;
        
        public GetMessagesRequest() {
        }
        
        public GetMessagesRequest(WebChat02.ChatServiceReference.GetMessagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessagesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public GetMessagesRequestBody() {
        }
        
        public GetMessagesRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessagesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebChat02.ChatServiceReference.GetMessagesResponseBody Body;
        
        public GetMessagesResponse() {
        }
        
        public GetMessagesResponse(WebChat02.ChatServiceReference.GetMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMessagesResponseBody {
        
        public GetMessagesResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMsgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMsg", Namespace="http://tempuri.org/", Order=0)]
        public WebChat02.ChatServiceReference.SendMsgRequestBody Body;
        
        public SendMsgRequest() {
        }
        
        public SendMsgRequest(WebChat02.ChatServiceReference.SendMsgRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMsgRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebChat02.ChatServiceReference.Msg incoming;
        
        public SendMsgRequestBody() {
        }
        
        public SendMsgRequestBody(WebChat02.ChatServiceReference.Msg incoming) {
            this.incoming = incoming;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMsgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMsgResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebChat02.ChatServiceReference.SendMsgResponseBody Body;
        
        public SendMsgResponse() {
        }
        
        public SendMsgResponse(WebChat02.ChatServiceReference.SendMsgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendMsgResponseBody {
        
        public SendMsgResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public WebChat02.ChatServiceReference.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(WebChat02.ChatServiceReference.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebChat02.ChatServiceReference.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(WebChat02.ChatServiceReference.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LoginResponseBody {
        
        public LoginResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChatServiceSoapChannel : WebChat02.ChatServiceReference.ChatServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatServiceSoapClient : System.ServiceModel.ClientBase<WebChat02.ChatServiceReference.ChatServiceSoap>, WebChat02.ChatServiceReference.ChatServiceSoap {
        
        public ChatServiceSoapClient() {
        }
        
        public ChatServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChatServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChatServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChatServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetOnlineUsers() {
            base.Channel.GetOnlineUsers();
        }
        
        public System.Threading.Tasks.Task GetOnlineUsersAsync() {
            return base.Channel.GetOnlineUsersAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebChat02.ChatServiceReference.GetMessagesResponse WebChat02.ChatServiceReference.ChatServiceSoap.GetMessages(WebChat02.ChatServiceReference.GetMessagesRequest request) {
            return base.Channel.GetMessages(request);
        }
        
        public void GetMessages(string username) {
            WebChat02.ChatServiceReference.GetMessagesRequest inValue = new WebChat02.ChatServiceReference.GetMessagesRequest();
            inValue.Body = new WebChat02.ChatServiceReference.GetMessagesRequestBody();
            inValue.Body.username = username;
            WebChat02.ChatServiceReference.GetMessagesResponse retVal = ((WebChat02.ChatServiceReference.ChatServiceSoap)(this)).GetMessages(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebChat02.ChatServiceReference.GetMessagesResponse> WebChat02.ChatServiceReference.ChatServiceSoap.GetMessagesAsync(WebChat02.ChatServiceReference.GetMessagesRequest request) {
            return base.Channel.GetMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebChat02.ChatServiceReference.GetMessagesResponse> GetMessagesAsync(string username) {
            WebChat02.ChatServiceReference.GetMessagesRequest inValue = new WebChat02.ChatServiceReference.GetMessagesRequest();
            inValue.Body = new WebChat02.ChatServiceReference.GetMessagesRequestBody();
            inValue.Body.username = username;
            return ((WebChat02.ChatServiceReference.ChatServiceSoap)(this)).GetMessagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebChat02.ChatServiceReference.SendMsgResponse WebChat02.ChatServiceReference.ChatServiceSoap.SendMsg(WebChat02.ChatServiceReference.SendMsgRequest request) {
            return base.Channel.SendMsg(request);
        }
        
        public void SendMsg(WebChat02.ChatServiceReference.Msg incoming) {
            WebChat02.ChatServiceReference.SendMsgRequest inValue = new WebChat02.ChatServiceReference.SendMsgRequest();
            inValue.Body = new WebChat02.ChatServiceReference.SendMsgRequestBody();
            inValue.Body.incoming = incoming;
            WebChat02.ChatServiceReference.SendMsgResponse retVal = ((WebChat02.ChatServiceReference.ChatServiceSoap)(this)).SendMsg(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebChat02.ChatServiceReference.SendMsgResponse> WebChat02.ChatServiceReference.ChatServiceSoap.SendMsgAsync(WebChat02.ChatServiceReference.SendMsgRequest request) {
            return base.Channel.SendMsgAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebChat02.ChatServiceReference.SendMsgResponse> SendMsgAsync(WebChat02.ChatServiceReference.Msg incoming) {
            WebChat02.ChatServiceReference.SendMsgRequest inValue = new WebChat02.ChatServiceReference.SendMsgRequest();
            inValue.Body = new WebChat02.ChatServiceReference.SendMsgRequestBody();
            inValue.Body.incoming = incoming;
            return ((WebChat02.ChatServiceReference.ChatServiceSoap)(this)).SendMsgAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebChat02.ChatServiceReference.LoginResponse WebChat02.ChatServiceReference.ChatServiceSoap.Login(WebChat02.ChatServiceReference.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public void Login(string username) {
            WebChat02.ChatServiceReference.LoginRequest inValue = new WebChat02.ChatServiceReference.LoginRequest();
            inValue.Body = new WebChat02.ChatServiceReference.LoginRequestBody();
            inValue.Body.username = username;
            WebChat02.ChatServiceReference.LoginResponse retVal = ((WebChat02.ChatServiceReference.ChatServiceSoap)(this)).Login(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebChat02.ChatServiceReference.LoginResponse> WebChat02.ChatServiceReference.ChatServiceSoap.LoginAsync(WebChat02.ChatServiceReference.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebChat02.ChatServiceReference.LoginResponse> LoginAsync(string username) {
            WebChat02.ChatServiceReference.LoginRequest inValue = new WebChat02.ChatServiceReference.LoginRequest();
            inValue.Body = new WebChat02.ChatServiceReference.LoginRequestBody();
            inValue.Body.username = username;
            return ((WebChat02.ChatServiceReference.ChatServiceSoap)(this)).LoginAsync(inValue);
        }
    }
}
